require:
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 2.5
  Exclude:
    - 'bin/**/*'
    - 'config/**/*'
    - 'db/**/*'
    - 'node_modules/**/*'
    - 'tmp/**/*'
    - 'vendor/**/*'
    - 'utils/**/*'
  SuggestExtensions: false
  NewCops: enable

Style/Documentation:
  Enabled: false

Bundler/OrderedGems:
  Enabled: false

########## NAMING RELATED
# Renaming `has_something?` to `something?` obfuscates whether it is a "is-a" or
# a "has-a" relationship.
Naming/PredicateName:
  Enabled: false

Naming/MethodParameterName:
  Enabled: false

Layout/EmptyLinesAroundModuleBody:
  Enabled: false

Layout/EmptyLinesAroundClassBody:
  Enabled: false

Layout/DotPosition:
  EnforcedStyle: trailing

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Layout/HashAlignment:
  EnforcedColonStyle: table
  EnforcedHashRocketStyle: table

Layout/FirstArrayElementIndentation:
  EnforcedStyle: consistent

Layout/BeginEndAlignment:
  Enabled: true

Layout/EmptyLinesAroundAttributeAccessor:
  Enabled: true

Layout/SpaceAroundMethodCallOperator:
  Enabled: true

########## STYLE RELATED
Style/EmptyElse:
  EnforcedStyle: empty

Style/FrozenStringLiteralComment:
  EnforcedStyle: always
  Exclude:
    - 'spec/**/*'

Style/IfUnlessModifier:
  Enabled: false

Style/SymbolArray:
  EnforcedStyle: brackets

Style/NumericPredicate:
  EnforcedStyle: comparison

Style/ZeroLengthPredicate:
  Enabled: false

Style/NegatedIf:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/EmptyMethod:
  Enabled: false

Style/MultilineTernaryOperator:
  Enabled: false

Style/DoubleNegation:
  Enabled: false

Style/SingleLineBlockParams:
  Enabled: false

Style/RedundantCondition:
  Enabled: false

Style/TrailingUnderscoreVariable:
  Enabled: false

Style/MultilineBlockChain:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Style/RedundantReturn:
  Enabled: false

Style/HashConversion:
  Enabled: true

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

Style/TernaryParentheses:
  EnforcedStyle: require_parentheses_when_complex

Style/FloatDivision:
  Enabled: false

Style/CommentedKeyword:
  Enabled: false

Lint/EmptyWhen:
  Enabled: false

Lint/RaiseException:
  Enabled: true

Lint/StructNewOverride:
  Enabled: true

Lint/BinaryOperatorWithIdenticalOperands:
  Enabled: true

Lint/ConstantDefinitionInBlock:
  Enabled: true

Lint/DeprecatedOpenSSLConstant:
  Enabled: true

Lint/DuplicateElsifCondition:
  Enabled: false

Lint/DuplicateRequire:
  Enabled: false

Lint/DuplicateRescueException:
  Enabled: false

Lint/EmptyConditionalBody:
  Enabled: false

Lint/EmptyFile:
  Enabled: false

Lint/FloatComparison:
  Enabled: false

Lint/HashCompareByIdentity:
  Enabled: false

Lint/IdentityComparison:
  Enabled: false

Lint/MissingSuper:
  Enabled: false

Lint/MixedRegexpCaptureTypes:
  Enabled: false

Lint/NumberedParameterAssignment:
  Enabled: true

Lint/OrAssignmentToConstant:
  Enabled: true

Lint/OutOfRangeRegexpRef:
  Enabled: false

Lint/RedundantSafeNavigation:
  Enabled: false

Lint/SelfAssignment:
  Enabled: false

Lint/SymbolConversion:
  Enabled: true

Lint/TopLevelReturnWithArgument:
  Enabled: false

Lint/TrailingCommaInAttributeDeclaration:
  Enabled: false

Lint/TripleQuotes:
  Enabled: true

Lint/UnreachableLoop:
  Enabled: false

Lint/UselessMethodDefinition:
  Enabled: false

Lint/UselessTimes:
  Enabled: false

# Disabled as a suggestion from https://github.com/rubocop-hq/rubocop/issues/4222
Lint/AmbiguousBlockAssociation:
  Exclude:
    - "spec/**/*.rb"

Style/AccessorGrouping:
  Enabled: false

Style/BisectedAttrAccessor:
  Enabled: false

Style/CaseLikeIf:
  Enabled: false

Style/ClassEqualityComparison:
  Enabled: false

Style/CombinableLoops:
  Enabled: false

Style/ExplicitBlockArgument:
  Enabled: false

Style/ExponentialNotation:
  Enabled: false

Style/GlobalStdStream:
  Enabled: false

Style/HashAsLastArrayItem:
  Enabled: false

Style/HashLikeCase:
  Enabled: false

Style/IfWithBooleanLiteralBranches:
  Enabled: true

Style/KeywordParametersOrder:
  Enabled: false

Style/OptionalBooleanParameter:
  Enabled: false

Style/RedundantAssignment:
  Enabled: false

Style/RedundantFetchBlock:
  Enabled: false

Style/RedundantFileExtensionInRequire:
  Enabled: false

Style/RedundantRegexpCharacterClass:
  Enabled: false

Style/RedundantRegexpEscape:
  Enabled: false

Style/RedundantSelfAssignment:
  Enabled: false

Style/SingleArgumentDig:
  Enabled: false

Style/SlicingWithRange:
  Enabled: false

Style/SoleNestedConditional:
  Enabled: false

Style/StringConcatenation:
  Enabled: false

########## METRICS RELATED
Metrics/AbcSize:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Metrics/ParameterLists:
  Max: 6

Style/FormatStringToken:
  Enabled: false

Lint/DuplicateBranch:
  Enabled: true
Lint/DuplicateRegexpCharacterClassElement:
  Enabled: true
Lint/EmptyBlock:
  Enabled: true
  Exclude:
    - "**/*_spec.rb"
Lint/EmptyClass:
  Enabled: true
Lint/NoReturnInBeginEndBlocks:
  Enabled: true
Lint/ToEnumArguments:
  Enabled: true
Lint/UnmodifiedReduceAccumulator:
  Enabled: true
Style/ArgumentsForwarding:
  Enabled: true
Style/CollectionCompact:
  Enabled: true
Style/DocumentDynamicEvalDefinition:
  Enabled: true
Style/NegatedIfElseCondition:
  Enabled: true
Style/NilLambda:
  Enabled: true
Style/RedundantArgument:
  Enabled: false
Style/SwapValues:
  Enabled: true

Lint/UnexpectedBlockArity:
  Enabled: true

Lint/AmbiguousAssignment:
  Enabled: true
Style/HashExcept:
  # Ruby 3.0.0 adds Hash#except, all ActiveSupport methods like Hash#reject, etc can be replaced with this native
  # function, once we switch to Ruby 3.0.0. We can enable this cop when we upgrade.
  # See: https://www.rubydoc.info/gems/rubocop/RuboCop/Cop/Style/HashExcept
  Enabled: false


Lint/DeprecatedConstants:
  Enabled: true
Lint/LambdaWithoutLiteralBlock:
  Enabled: true
Lint/RedundantDirGlobSort:
  Enabled: true
Style/EndlessMethod:
  Enabled: true

Naming/VariableNumber:
  Enabled: false

Gemspec/DateAssignment:
  Enabled: true

Style/StringChars:
  Enabled: true

Lint/EmptyInPattern:
  Enabled: true

Style/InPatternThen:
  Enabled: true

Style/MultilineInPatternThen:
  Enabled: true

Style/QuotedSymbols:
  Enabled: true

Layout/LineEndStringConcatenationIndentation:
  Enabled: true

Naming/InclusiveLanguage:
  Enabled: false
  Severity: info

Lint/AmbiguousRange:
  Enabled: true

Style/RedundantSelfAssignmentBranch:
  Enabled: true

# ---------------------------------------------------------------------------------------------------------------------
# RuboCop RSpec Config

RSpec/AnyInstance:
  Enabled: false

RSpec/BeEql:
  Enabled: false

RSpec/Capybara/VisibilityMatcher:
  Enabled: true

RSpec/EmptyHook:
  Enabled: true

RSpec/EmptyLineAfterExampleGroup:
  Enabled: true

RSpec/ExampleLength:
  Enabled: false

RSpec/InstanceVariable:
  Enabled: true

RSpec/MessageSpies:
  Enabled: true
  EnforcedStyle: receive

RSpec/MultipleExpectations:
  Enabled: false

RSpec/MultipleMemoizedHelpers:
  Enabled: false

RSpec/NamedSubject:
  Enabled: false

RSpec/StubbedMock:
  Enabled: false

RSpec/VariableName:
  EnforcedStyle: snake_case
  IgnoredPatterns:
    - '^X-'
    - 'Authorization'

RSpec/IdenticalEqualityAssertion:
  Enabled: true

RSpec/DescribeClass:
  Exclude:
    - spec/ioki/vcr/*
    - spec/ioki/model/openapi_spec.rb

RSpec/NestedGroups:
  Max: 4
