AllCops:
  TargetRubyVersion: 2.7

inherit_from:
  - https://dbdrive.github.io/triebwerk/rubocop_common.yml

# Custom configuration
RSpec/DescribeClass:
  Exclude:
    - spec/ioki/examples/*
    - spec/ioki/model/openapi_spec.rb

RSpec/NestedGroups:
  Max: 4
