AllCops:
  TargetRubyVersion: 3.0

inherit_from:
  - https://dbdrive.github.io/triebwerk/rubocop_common.yml

# Custom configuration
Metrics/ParameterLists:
  Exclude:
    - 'lib/ioki/apis/endpoints/create.rb'
    - 'lib/ioki/apis/endpoints/endpoint.rb'

Style/OpenStructUse:
  Enabled: no

RSpec/DescribeClass:
  Exclude:
    - spec/ioki/examples/*
    - spec/ioki/model/openapi_spec.rb

RSpec/NestedGroups:
  Max: 4
