# frozen_string_literal: true

require 'ioki/model/base'
require 'ioki/model/driver/base'
require 'ioki/model/driver/driver_request_token'
require 'ioki/model/driver/product'

require 'ioki/model/passenger/base'
require 'ioki/model/passenger/bootstrap'
require 'ioki/model/passenger/cancellation'
require 'ioki/model/passenger/features'
require 'ioki/model/passenger/phone_verification_request'
require 'ioki/model/passenger/product'
require 'ioki/model/passenger/provider'
require 'ioki/model/passenger/ride_inquiry'
require 'ioki/model/passenger/user_phone_number'

require 'ioki/model/platform/area'
require 'ioki/model/platform/base'
require 'ioki/model/platform/booking'
require 'ioki/model/platform/calculated_point'
require 'ioki/model/platform/client'
require 'ioki/model/platform/deactivation'
require 'ioki/model/platform/driver'
require 'ioki/model/platform/driver_emergency'
require 'ioki/model/platform/driver_vehicle_connection'
require 'ioki/model/platform/journey'
require 'ioki/model/platform/passenger_request_token'
require 'ioki/model/platform/pause'
require 'ioki/model/platform/payment_method'
require 'ioki/model/platform/product'
require 'ioki/model/platform/provider'
require 'ioki/model/platform/rating'
require 'ioki/model/platform/receipt'
require 'ioki/model/platform/requested_point'
require 'ioki/model/platform/ride'
require 'ioki/model/platform/ride_inquiry'
require 'ioki/model/platform/ride_passenger'
require 'ioki/model/platform/service_credit'
require 'ioki/model/platform/station'
require 'ioki/model/platform/task_list'
require 'ioki/model/platform/user'
require 'ioki/model/platform/user_email'
require 'ioki/model/platform/vehicle'
require 'ioki/model/platform/webhook'

module Ioki
  module Model
  end
end
