name: CI for all of ioki-ruby

on: [push]

jobs:
  linting:
    runs-on: ubuntu-latest

    steps:
      - name: Pull repository
        uses: actions/checkout@v7
      - name: Bundle install and cache result
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - name: Run rubocop
        run: |
          bundle exec rubocop --ignore-unrecognized-cops

  tests:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    name: Ruby ${{ matrix.ruby }}
    strategy:
      matrix:
        ruby:
          - '3.3.12'
          - '3.4.11'
          - '4.0.7'

    steps:
      - name: Pull repository
        uses: actions/checkout@v7
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Run rspec tests
        run: |
          source .github/ci_workflow.env
          bundle exec rspec
